# Generated by Django 6.0.7 on 2026-09-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
