# Generated by Django 6.0.7 on 2026-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_app_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default='5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(default=True),
        ),
    ]
