# Generated by Django 6.0.7 on 2026-10-03 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='mainapp.category'),
        ),
    ]
